minVersion: "0.12.0"
github:
  owner: corydodt
  repo: jobbergate-cli
releaseBranchPrefix: release
changelog: CHANGELOG.md
changelogPolicy: auto
statusProvider:
  name: github
  config:
    contexts:
      - "ReleaseAction"
artifactProvider:
  name: github
targets:
  - name: github
