[tool.poetry]
name = "jobbergate-cli"
version = "1.2.1"
description = "Jobbergate CLI Client"
authors = ["Omnivector Solutions <info@omnivector.solutions>"]
license = "MIT"
packages = [ { include = "jobbergate_cli" } ]
repository = "https://github.com/omnivector-solutions/jobbergate-cli"
documentation = "https://omnivector-solutions.github.io/jobbergate-cli"


[tool.poetry.dependencies]
python = "^3.6.2"
click = "^8.0.1"
inquirer = "^2.7.0"
PyJWT = "<2"
PyYAML = "^5.4.1"
python-dotenv = "^0.19.0"
requests = "^2.26.0"
tabulate = "^0.8.9"
urllib3 = "^1.26.7"
sentry-sdk = "^1.4.3"
boto3 = "^1.18.64"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest-cov = "^3.0.0"
pytest-random-order = "^1.0.4"
pytest-freezegun = "^0.4.2"
pytest-responsemock = "^1.0.1"
flake8 = "^3.9.2"
isort = "^5.9.3"
pytest-env = "^0.6.2"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--random-order --cov=jobbergate_cli --cov-report=term-missing --cov-fail-under=25"
env = [
    "JOBBERGATE_API_ENDPOINT = https://jobbergate-api-staging.omnivector.solutions",
    "JOBBERGATE_DEBUG = false",
]
testpaths = ["jobbergate_cli/test"]

[tool.black]

[tool.isort]
lines_after_imports = "2"
# ignore from..import vs import while sorting a section
force_sort_within_sections = "1"
profile = "black"

[tool.poetry.scripts]
jobbergate = "jobbergate_cli.main:main"
jobbergate-legacy = "jobbergate_cli.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
