name: Test

on: pull_request

jobs:
  test:
    name: "Check quality"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: 'x64'
      - uses: Gr1N/setup-poetry@v7
      - name: "Run Tests"
        run: |
          make qa
